### ISSUE TITLE
[feature request] please print how much heap is in use (in bytes)

### ISSUE THREAD

**Issue by rgolangh** [subns/test#11]
As a user I want `main.go` to print how much memory the heap is using

Expected behaviour:
```
$ go run main.go --printMemUsage
Heap in use: 442368 bytes
```

**Comment by rgolangh** [comment]
@liadlauber can you please take this?

**Comment by rgolangh** [comment]
should be `printMemUsage` and not printmem. Fixing the issue description

**Comment by liadlauber** [comment]
addressed in #14
