### ISSUE TITLE
The main doesn't print the current time

### ISSUE THREAD

**Issue by rgolangh** [subns/test#8]
As a user, I expect that `main.go` execution would print the current time.

Exepected behaviour:
```
09:25 $ go run main.go 
current time: 2022-05-31 09:25:41.013067829 +0300 IDT m=+0.000023232
```

**Comment by rgolangh** [comment]
@nadavdolin can you take this?

**Comment by nadavdolin** [comment]
Hello @rgolangh I fixed the issue and send a pr
